In [2]:
import numpy as np
import random

Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [3]:
arr=np.random.randint([5])
arr

array([3])

Given a NumPy array 'arr', check if its data type is float64.

In [4]:
arr = np.array([1.5, 2.6, 3.7])
arr.dtype==float

True

Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [5]:
arr=np.complex128([1])
arr

array([1.+0.j])

 Convert an existing NumPy array 'arr' of integers to float32 data type.

In [6]:
arr=np.array([1,2,3])
new_arr=np.float32(arr)
new_arr

array([1., 2., 3.], dtype=float32)

Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [7]:
arr = np.float64([1,2,3])
new_arr=np.float32([arr])
new_arr

array([[1., 2., 3.]], dtype=float32)

 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data 
type

In [8]:
def array_attributes():
    element=np.array(input().split(),dtype=int)
    siz=element.size
    ship=element.shape
    dat=element.dtype
    return siz ,ship,dat,element
siz,ship,dat,arr=array_attributes()
print("Size:", siz)
print("Shape:", ship)
print("Data type:", dat)
print("Array:", arr)
    

Size: 4
Shape: (4,)
Data type: int32
Array: [1 2 3 4]


 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [9]:
def array_dimension():
    array=np.array(input().split())
    return new_arr.ndim
arr=array_dimension()
print(arr)

2


 Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
size in bytes.

In [10]:
def item_size_info():
    arr=np.array(input().split())
    size=arr.itemsize
    b_size=size*8
    return size,b_size
size,b_size=item_size_info()
print(size,b_size)

4 32


 Create a function array_strides that takes a NumPy array as input and returns the strides of the array

Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
and strides of the array.

Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
zeros with `n` elements

In [11]:
def create_zeros_array():
    n=int(input())
    arr=np.zeros(n)
    return arr
arr = create_zeros_array()    
arr

ValueError: invalid literal for int() with base 10: '1 2 3 4 5'

Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
NumPy array filled with ones of size `rows x cols`.

In [ ]:
def create_ones_matrix():
    rows=int(input())
    cols=int(input())
    arr=np.ones((rows,cols))
    return arr
arr=create_ones_matrix()
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`.

In [ ]:
def generate_range_array():
    start=int(input())
    stop=int(input())
    step=int(input())
    arr=np.arange(start,stop,step)
    return arr
arr=generate_range_array()
arr

array([1, 3, 5, 7])

Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive)

In [ ]:
def generate_linear_space():
    start=float(input())
    stop=float(input())
    num=int(input())
    arr=np.arange(start,stop,num)
    return arr
arr=generate_linear_space()
arr

array([1., 3., 5., 7., 9.])

Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
def create_identity_matrix():
    n=int(input())
    iden=np.eye(n,n)
    return iden
iden=create_identity_matrix()
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 Write a function that takes a Python list and converts it into a NumPy array

In [ ]:
def list_to_numpy():
    list=input().split()
    arr=np.array(list)
    return arr
arr=list_to_numpy()
arr

array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
same data.

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
view_arr=arr.view()
view_arr[0]=100
view_arr



array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
arr1=np.array([1,2,3,])
arr2=np.array([4,5,6,])
arr3=np.concatenate((arr1,arr2),axis=0)
arr3

array([1, 2, 3, 4, 5, 6])

Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

In [ ]:
arr1=np.array([1,2,3,])
arr2=np.array([4,5,6,])
arr3=np.concatenate((arr1,arr2),axis=0)
arr3

array([1, 2, 3, 4, 5, 6])

Write a function that vertically stacks multiple NumPy arrays given as a list.

In [13]:
def vertically_stack_arrays(arrays):

    return np.vstack(arrays)
a1=np.array([[1,2,3],
             [2,3,4]])
a2=np.array([[3,4,5],
             [5,6,7]])
a3=vertically_stack_arrays([a1,a2])


print(a3)

    

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [5 6 7]]


Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size. 

In [40]:
def arr_range(stop,ste):
    arr=np.arange(0,stop+ste,ste)
    if arr[-1]>ste:
        arr=np.delete(arr,-1)
        return arr
    else:
        return arr 
stop=20
step=3
arr=arr_range(stop,step)
arr

array([ 0,  3,  6,  9, 12, 15, 18])

 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
(inclusive).  



In [41]:
def equi_arr():
    arr=np.linspace(0,1,10)
    return arr
arr=equi_arr()
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
1000 (inclusive).  

In [47]:
#cheack this code
def equi_arr():
    arr=np.logspace(1,3,5)
    return arr
arr=equi_arr()
arr

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100. 

In [61]:
import pandas as pb
arr=np.random.randint(1,100,size=15)
arr=arr.reshape(5,3)
arr=pb.DataFrame(arr)
arr

0   1   2
0  34   1  65
1  35   6  96
2  16  50  76
3  63  69  29
4  22  59  55

Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame. 

In [93]:
def zero_find(arr,a):
    arr[a]=np.where(arr[a]<0,0,arr[a])
    return arr
data={'A':[-1,2,-3,4],
      'B':[1,-2,3,4]}
df=pb.DataFrame(data)
arr=zero_find(df,'A')
arr

A  B
0  0  1
1  2 -2
2  0  3
3  4  4

 Access the 3rd element from the given NumPy array.

 

 arr = np.array([10, 20, 30, 40, 50])

In [94]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

 Retrieve the element at index (1, 2) from the 2D NumPy array.    

arr_2d = np.array([[1, 2, 3],                    [4, 5, 6], 
                   [7, 8, 9]])

In [106]:
arr_2d = np.array([[1, 2, 3],                    
                   [4, 5, 6], 
                   [7, 8, 9]])
elements=[1,2]
element_index=np.where(np.isin(arr_2d, elements))
print(f"element fitst index{element_index[0]} secound element index{element_index[1]}")


element fitst index[0 0] secound element index[0 1]


 Using boolean indexing, extract elements greater than 5 from the given NumPy array.   

arr = np.array([3, 8, 2, 10, 5, 7])

In [128]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr_new=arr[arr>5]
arr_new

array([ 8, 10,  7])

 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.   

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr=arr[2:6]
new_arr

array([3, 4, 5, 6])

 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array

arr_2d = np.array([[1, 2, 3],                    [4, 5, 6], 
                   [7, 8, 9]])

In [134]:
arr_2d = np.array([[1, 2, 3],                    
                   [4, 5, 6], 
                   [7, 8, 9]])
new_2d_array=arr_2d[0:2]
new_2d_array

array([[1, 2, 3],
       [4, 5, 6]])