In [1]:
import numpy as np

In [5]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [99]:
import random

In [129]:
def element_finder(arr,ind):
    arr=arr.flatten()
    final_arr=arr[ind]
    return final_arr
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices=np.array([1,5,6])
final_elements=element_finder(arr_2d,indices)
final_elements


array([2, 6, 7])

Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [137]:
def element_remover(arr,val):
    arr=arr[arr>val]
    return arr
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr=arr_2d.flatten()
val =5
arr=element_remover(arr,val)
arr

array([6, 7, 8, 9])

 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [158]:
def ele_return(arr,a,b,c):
    element=[]
    for i in range(len(a)):
        element.append(arr[a[i]][b[i]][c[i]])
    return element
    
arr_3d = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
d1=np.array([0,0])
d2=np.array([1,2])
d3=np.array([2,1])
element=ele_return(arr_3d,d1,d2,d3)
element

[6, 8]

Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing

In [ ]:
def element_remover( arr,con1,con2):
    combine_condition=np.logical_and(con1,con2)
    arr=arr[combine_condition]
    return arr
arr_3d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr=arr_3d.flatten()
cond1=arr%2==0
cond2=arr>1
element=element_remover(arr,cond1,cond2)
element


Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [219]:
def ret(arr,row,col):
    element=[]
    for i in range(len(row)):
        element=arr[row,col]
    return element 
arr_3d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row=np.array([1,0,])
col=np.array([0,2])
element=ret(arr_3d,row,col)
element
    

array([4, 3])

6. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [227]:
arr=np.zeros([3,3])
arr=arr+5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [31]:
arr1=np.random.randint(1,4,size=(1,3))
arr2=np.random.randint(5,7,size=(3,4))
arr4=arr1.T*arr2
arr4

array([[ 6,  6,  5,  6],
       [18, 18, 15, 15],
       [ 6,  6,  6,  5]])

Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [19]:
arr1=np.random.randint(1,4,size=(3))
arr2=np.random.randint(1,4,size=(2,3))
arr3=arr1+arr2
arr3

array([[4, 5, 2],
       [3, 6, 4]])

Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [23]:
arr1=np.random.randint(1,4,size=(3,1))
arr2=np.random.randint(5,7,size=(1,3))
arr3=arr1+arr2
arr3

array([[7, 6, 7],
       [8, 7, 8],
       [7, 6, 7]])

Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [3]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape: (2, 3)

arr2 = np.array([[7, 8],
                 [9, 10]]) 
arr3=np.dot(arr1.T,arr2)
arr3

array([[43, 48],
       [59, 66],
       [75, 84]])

Calculate column wise mean for the given array

arr = np.array([[1, 2, 3], [4, 5, 6]])


In [70]:
import pandas as pb
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean=[]
row,col=arr.shape
mean=np.mean(arr,axis=0)        
mean


array([2.5, 3.5, 4.5])

 Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [71]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
r_max=np.max(arr,axis=1)
r_max

array([3, 6])

For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [78]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
r_max_index=np.argmax(arr,axis=0)
r_max_index

array([1, 1, 1])

For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [97]:
def moving_sum(arr,window):
    movin_sum_arr=np.zeros_like(arr)
    #np.zeros_like
    #Creates a new array with the same shape and type as the given array but filled with zeros.
    row,col=arr.shape
    for i in range(row):
        for j in range(col-window+1):
            movin_sum_arr[i,j+window-1]=np.sum(arr[i,j:j+window])
    return movin_sum_arr
arr = np.array([[1, 2, 3], [4, 5, 6]])
window=2
new_arr=moving_sum(arr,window)
new_arr

array([[ 0,  3,  5],
       [ 0,  9, 11]])

In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

In [113]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
cond=arr%2==0
n_r=np.all(cond,axis=0)
n_r

array([False, False, False])

 Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.





original_array = np.array([1, 2, 3, 4, 5, 6])

In [129]:
import math
original_array = np.array([1, 2, 3, 4, 5, 6])
met=original_array.reshape(2,3)
met=np.matrix(met)
met

matrix([[1, 2, 3],
        [4, 5, 6]])

Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
input_matrix = np.matrix([[1, 2, 3], [4, 5, 6]])
arr=np.array(input_matrix).flatten()
arr

array([1, 2, 3, 4, 5, 6])

 Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])


In [11]:
def con(arr1,arr2):
    arr3=np.concatenate((arr1,arr2),axis=1)
    return arr3
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
arr3=con(array1,array2)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Create a function that splits an array into multiple sub-arrays along a specified axis

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [563]:
#doubt
#question no 50
import numpy as np
def split_fun(arr,splits,axis):
    new=np.split(arr,splits,axis=axis)
    return new
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
splits=3
axis=1
sub_str=split_fun(original_array,splits,axis)
sub_str


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [77]:
arr1=np.random.randint(10,size=10)
arr2=np.arange(1,11)
arr3=np.add(arr1,arr2)
arr3

array([ 6,  7,  9, 10,  7,  7,  9, 16, 11, 19])

52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise

In [75]:
arr2=np.arange(1,10)
arr1=arr2[::-1]
arr3=np.subtract(arr2,arr2)
arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [72]:
arr1=np.random.randint(5,10,size=5)
arr2=np.arange(1,6)
arr3=np.multiply(arr1,arr2)
arr3

array([ 7, 18, 18, 24, 45])

54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [70]:
arr1=np.arange(1,11)
arr1=arr1[arr1%2==0]
arr2=np.arange(1,6)
arr3=np.divide(arr1,arr2)
arr3

array([2., 2., 2., 2., 2.])

55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

In [66]:
arr1=np.arange(1,6)
arr2=arr1[::-1]
arr3=np.power(arr1,arr2)
arr3

array([ 1, 16, 27, 16,  5])

In [63]:
arr1,arr2

(array([1, 2, 3, 4, 5]), array([5, 4, 3, 2, 1]))

 Write a function that counts the occurrences of a specific substring within a NumPy array of strings

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


In [564]:
def occurance(arr,substring):
    count=np.char.count(arr,substring)
    count=np.sum(count)
    return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substiong='hello'
count=occurance(arr,substiong)
count



3

 Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [547]:

#ask in doubt season
import numpy as np

def extract_uppercase(arr):
    return np.array([''.join(char for char in word if char.isupper()) for word in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print("Uppercase characters:", uppercase_chars)


Uppercase characters: ['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [151]:
def replace(arr,a,b):
    new_arr=np.char.replace(arr,a,b)
    return new_arr
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
substr='apple'
reple_it='no_apple'
arr=replace(arr,substr,reple_it)
arr
        
    

array(['no_apple', 'banana', 'grape', 'pineno_apple'], dtype='<U12')

59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])

In [160]:
def con(arr1,arr2):
    new_arr=np.char.add(arr1,arr2)
    return new_arr
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
arr3=con(arr1,arr2)
arr3

array(['HelloOpen', 'WorldAI'], dtype='<U9')

60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [193]:
def len_fun(arr):
    vectorized_len = np.vectorize(len)
    leng=vectorized_len(arr)
    max=leng.max()
    ele=np.where(leng==max)
    return ele
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
chare=len_fun(arr)
arr[chare]


(array([0]), array([3]))

61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [213]:
import pandas as pd
arr=np.random.randint(1,1000,100)
df=pd.DataFrame(arr)
mean=df.mean()
median=df.median()
variance=df.var()
std=df.std()
mean,median,variance,std


(0    509.07
 dtype: float64,
 0    521.0
 dtype: float64,
 0    95429.237475
 dtype: float64,
 0    308.916231
 dtype: float64)

62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [222]:
arr=np.random.randint(1,100,50)
per_25=np.percentile(arr,25)
per_75=np.percentile(arr,75)
per_25,per_75

(35.75, 78.75)

 Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [224]:
arr1=np.random.randint(1,100,50)
arr2=np.random.randint(1,1000,100)
arr3=np.corrcoef(arr2,arr2)
arr3

array([[1., 1.],
       [1., 1.]])

 Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [234]:
arr1=np.random.randint(1,10,10)
arr2=np.random.randint(1,100,10)
met1=np.matrix(arr1)
met2=np.matrix(arr2)
dot_pro=np.dot(met1,met2.T)
dot_pro

matrix([[1922]])

65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [246]:
arr=np.random.randint(10,1000,50)
mean_10=np.percentile(arr,10)
mean_50=np.percentile(arr,50)
percentile_90=np.percentile(arr,90)
first_quartile=np.percentile(arr,25)
third_quartile=np.percentile(arr,75)
mean_10,mean_50,percentile_90,first_quartile,third_quartile

(57.8, 550.0, 934.5, 177.0, 732.75)

66. Create a NumPy array of integers and find the index of a specific element.

In [249]:
arr = np.array([1,2,3,4,5])
element=3
index=np.where(arr==element)
index

(array([2]),)

67. Generate a random NumPy array and sort it in ascending order.

In [260]:
arr=np.random.randint(1,20,10)
arr.sort()

array([ 2,  2,  2,  5, 10, 11, 13, 17, 17, 18])

68. Filter elements >20  in the given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

In [268]:
arr = np.array([12, 25, 6, 42, 8, 30])
fil_arr=arr[arr>20]
fil_arr

Filter elements which are divisible by 3 from a given NumPy array
arr = np.array([1, 5, 8, 12, 15])

In [284]:
arr = np.array([1, 5, 8, 12, 15])
cond=arr%3==0
new_arr=arr[cond]
new_arr

array([12, 15])

Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [305]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr >= 20) & (arr <= 40)]

array([20, 30, 40])

71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])


In [312]:
arr = np.array([1, 2, 3])
arr.dtype.byteorder
#doubt

'='

72. For the given NumPy array, perform byte swapping in place using `byteswap()
arr = np.array([1, 2, 3], dtype=np.int32)


In [323]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
arr

array([16777216, 33554432, 50331648], dtype=int32)

73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()

In [321]:
erarr = np.array([1, 2, 3], dtype=np.int32)
new_nyteord=arr.newbyteorder()
new_nyteorder



array([1, 2, 3], dtype=int32)

74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()

arr = np.array([1, 2, 3], dtype=np.int32)

In [338]:
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
if sys.byteorder == 'little':
    new_arr=arr.newbyteorder('>')
else:
     new_arr=arr.newbyteorder('<')
new_arr

array([16777216, 33554432, 50331648], dtype=int32)

75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [343]:
arr = np.array([1, 2, 3], dtype=np.int32)

array_byte_order = arr.dtype.byteorder

system_byte_order = np.dtype('<i4').byteorder

if array_byte_order != system_byte_order:
    print("Byte swapping is necessary for the current system.")
else:
    print("No byte swapping is necessary for the current system.")




No byte swapping is necessary for the current system.


 Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [374]:
arr=np.random.randint(1,10,12)
arr_copy=arr.copy()
arr_copy.reshape(4,3)
print(arr,arr_copy)
print(f"Yes it also modify the original arr")

[5 2 1 7 9 8 8 6 5 2 4 3] [5 2 1 7 9 8 8 6 5 2 4 3]
Yes it also modify the original arr


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [438]:
arr=np.array([[1,2,3],[2,3,4],[4,5,6]])
arr=arr.reshape(3,3)
print(arr)
view_slice=arr[1:2]
view_slice[0,1]=5
print(arr,view_slice)
print("It does change the original matrix")

[[1 2 3]
 [2 3 4]
 [4 5 6]]
[[1 2 3]
 [2 5 4]
 [4 5 6]] [[2 5 4]]
It does change the original matrix


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [444]:
array_a=np.arange(1,13)
array_a=array_a.reshape(4,3)
print(array_a)
view_b=array_a[1:2]
view_b=view_b+5
print(array_a,'\n\n',view_b)
print("It does not change the original matrix")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [[ 9 10 11]]
It does not change the original matrix


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [453]:
orig_array=np.arange(1,9)
orig_array=orig_array.reshape(2,4)
reshaped_view=orig_array.T
reshaped_view[0][0]=4
print(orig_array,'\n\n',reshaped_view)
print("It does change the original matrix")

[[4 2 3 4]
 [5 6 7 8]] 

 [[4 5]
 [2 6]
 [3 7]
 [4 8]]
It does change the original matrix


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [469]:
data=np.arange(1,13)
data=data.reshape(3,4)
data_copy=data.copy()[data>5]
data_copy[0]=9
print(data,'\n\n',data_copy)
print("It does not change the original matrix")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [ 9  7  8  9 10 11 12]
It does not change the original matrix


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [472]:
a=np.matrix([1,2,3,4,5,6])
b=np.matrix([9,8,7,6,5,4])
c=a+b
d=a-b
print(c,"\n\n",d)

[[10 10 10 10 10 10]] 

 [[-8 -6 -4 -2  0  2]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [487]:
c=np.arange(0,6)
d=np.arange(0,8)
c=np.matrix(c).reshape(3,2)
d=np.matrix(d).reshape(2,4)
e=c*d
f=c@d
g=np.dot(c,d)
e,f,g

(matrix([[ 4,  5,  6,  7],
         [12, 17, 22, 27],
         [20, 29, 38, 47]]),
 matrix([[ 4,  5,  6,  7],
         [12, 17, 22, 27],
         [20, 29, 38, 47]]),
 matrix([[ 4,  5,  6,  7],
         [12, 17, 22, 27],
         [20, 29, 38, 47]]))

Create a matrix `E` and find its transpose

In [494]:
e=np.arange(0,6).reshape(2,3)
e=np.matrix(e)
e_t=e.T
print(f"E{e} and its Transpose \n {e_t}")

E[[0 1 2]
 [3 4 5]] and its Transpose 
 [[0 3]
 [1 4]
 [2 5]]


Create a matrix `E` and find its transpose

84. Generate a square matrix `F` and compute its determinant.

In [545]:
F = np.random.randint(1, 10, size=(4, 4))
det_F = np.linalg.det(F)
det_F
#if det_F == 0 "Matrix G is singular and does not have an inverse."

53.99999999999996

85. Create a square matrix `G` and find its inverse.

In [546]:
G=np.arange(0,4).reshape(2,2)
G=np.matrix(G)
G_inv=np.linalg.inv(G)
G_inv

matrix([[-1.5,  0.5],
        [ 1. ,  0. ]])